CREATE TABLE IF NOT EXISTS question_scores (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    code VARCHAR(255) NOT NULL UNIQUE, 
    points INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS answer_scores (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    code VARCHAR(255) NOT NULL UNIQUE, 
    points INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);